global:
  server_host: 127.0.0.1
  server_port: 10008
  # Possible values: "streamable-http", "sse"
  server_transport: "streamable-http"

access:
  default:
    user: "admin"
    passwd: "admin@123"
    port: 830
  
  test: &test
    user: "admin"
    passwd: "admin@123"
    port: 830

devices:

  r1:
    host: 172.20.20.2
    user: "admin"
    passwd: "admin@123"

  r2:
    host: 172.20.20.3
    <<: *test

